build: false
clone_depth: 1
clone_folder: c:\projects\ginfo

environment:
    PHP_DIR: C:\tools\php

cache:
    - '%LOCALAPPDATA%\Composer\files'

init:
    - SET PATH=%PHP_DIR%;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - cinst php -y --params "/InstallDir:%PHP_DIR%"
    - copy /Y %PHP_DIR%\php.ini-development %PHP_DIR%\php.ini
    - echo extension_dir=ext >> %PHP_DIR%\php.ini
    - echo echo extension=php_mbstring.dll >> %PHP_DIR%\php.ini
    - cinst composer -y --ia "/DEV=%PHP_DIR%"
    - refreshenv
    - php -v
    - composer self-update
    - cd %APPVEYOR_BUILD_FOLDER%
    - composer install --no-interaction --ansi --no-progress --no-suggest --prefer-dist

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - vendor\bin\phpunit --configuration phpunit.xml.dist
