name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '8.2'
            job-description: 'Ubuntu; PHP 8.2; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.2'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 8.2; lowest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.3'
            job-description: 'Ubuntu; PHP 8.3; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.3'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 8.3; lowest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.4'
            job-description: 'Ubuntu; PHP 8.4; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.4'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 8.4; lowest-deps'

          - operating-system: 'windows-latest'
            php-version: '8.4'
            job-description: 'Windows; PHP 8.4; latest-deps'

          #- operating-system: 'macos-latest'
          #  php-version: '8.4'
          #  job-description: 'MacOS; PHP 8.4; latest-deps'


    name: ${{ matrix.job-description }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4
      - if: matrix.operating-system == 'ubuntu-latest'
        run: |
          wget https://repo.manticoresearch.com/manticore-repo.noarch.deb
          sudo dpkg -i manticore-repo.noarch.deb
          sudo curl -o /etc/apt/trusted.gpg.d/angie-signing.gpg https://angie.software/keys/angie-signing.gpg
          echo "deb https://download.angie.software/angie/$(. /etc/os-release && echo "$ID/$VERSION_ID $VERSION_CODENAME") main" > /etc/apt/sources.list.d/angie.list
          sudo apt install -y angie valkey mariadb-server postgresql-common manticore manticore-extra

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcre, mbstring, json
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          retry_wait_seconds: 30
          command: |
            composer update --optimize-autoloader --no-interaction --ansi --no-progress --prefer-dist ${{ matrix.composer-flags }}
            composer info -D

      - name: Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
